---
galaxy_info:
  author: Dreadnode
  namespace: dreadnode
  description: Redis server for Ares worker message broker
  company: dreadnode
  license: MIT
  role_name: redis
  min_ansible_version: "2.18.4"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Kali
      versions:
        - all
  galaxy_tags:
    - ares
    - redis
    - worker
    - broker
