---
collections:
  - name: amazon.aws
    version: 11.2.0
  - name: ansible.windows
    version: 3.5.0
  - name: community.windows
    version: 3.1.0
  - name: community.docker
    version: 5.2.0
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.5.0
  - name: grafana.grafana
    version: 6.0.6
  - name: https://github.com/CowDogMoo/ansible-collection-workstation.git
    type: git
    version: main
  - name: https://github.com/l50/ansible-collection-arsenal.git
    type: git
    version: main
