---
name: Pre-Commit
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  schedule:
    # Run once a week (see https://crontab.guru)
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: pre-commit-${{ github.workflow }}-${{ github.ref }}

env:
  GO_VERSION: "1.26.1"
  PYTHON_VERSION: "3.13.5"
  # ansible-lint v26 requires Python 3.14 for its pre-commit virtualenv
  PYTHON_VERSION_ANSIBLE_LINT: "3.14.3"
  TASK_X_REMOTE_TASKFILES: "1"
  TASK_VERSION: 3.49.1

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write # Allows merge queue updates

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python ${{ env.PYTHON_VERSION_ANSIBLE_LINT }} (for ansible-lint pre-commit hook)
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION_ANSIBLE_LINT }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '.hooks/requirements.txt'

      - name: Install dependencies
        run: python3 -m pip install -r .hooks/requirements.txt

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go module dependencies
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r ansible/requirements.yml --force --no-deps

      - name: Build and install local collection
        working-directory: ansible
        run: |
          ansible-galaxy collection build --force
          ansible-galaxy collection install dreadnode-nimbus_range-*.tar.gz -p ~/.ansible/collections --force --pre

      - name: Setup go-task
        env:
          TASK_VER: ${{ env.TASK_VERSION }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin "v${TASK_VER}"
          task --version

      - name: Run pre-commit
        run: task -y run-pre-commit
